// Document generation section.

export const DOC_GENERATION = `# Document Generation
- NO watermarks, NO "Generated by" footers
- Professional formatting: margins, headers, page numbers
- Include images when relevant
- Tables properly formatted`;
