services:
  db:
    image: postgres:15-alpine
    container_name: aurix-postgres
    restart: always
    environment:
      POSTGRES_USER: aurix_user
      POSTGRES_PASSWORD: aurix_password123!
      POSTGRES_DB: aurix_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    image: redis:7-alpine
    container_name: aurix-redis
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --requirepass aurix_redis_pass123!

volumes:
  postgres_data:
