/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function countTokens(text: string, encoding?: string | undefined | null): number
export declare function countTokensBatch(texts: Array<string>, encoding?: string | undefined | null): Array<number>
